### ISSUE TITLE
[Feature request] Adding a few frequently used, handy functionalities

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/sparse-lm#1]
1, Add a property function that returns CV not in the form of R2 score, but in the form of RMSE
2, Allow estimation of the variance of CV
3, Implement a child class of GridSearchCV that allows applying one standard error rule. I'm already sure this is not provided in sklearn by default. (requires 2)
4(optional): Implement a LineSearchCV on models with multiple hyper-params, just in case people want to automate mixedL0 models.

I'll PR when these are available.

**Comment by lbluque** [comment]
fixed in #6
