### ISSUE TITLE
[Bug] base.py Estimator's .coef_ attribute will fool sklearn.model.validation's check_is_fitted

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/sparse-lm#4]
When using GridSearchCV, sklearn will frequently call a function "check_is_fitted" to see whether a model is fitted or not, so that it can mute some unavailable functions for un-fitted models.

When no specific attribute is provided to check_is_fitted (which is the case that happens in GridSearchCV source code), sklearn simply checks whether a model has any attribute whose name ends with an underscore by scanning estimator's __dict__.

In Line 50 of base.py, we explicitly assigned attributes: 
`        self.coef_, self.intercept_ = None, None`
Although these are assigned None, they will still fool scikit-learn into believing the model has been fitted. And by inspecting the codes I haven't found any good reason to pre-assign coef_ and intercept_ attributes in __init__. This line of code should be removed.

If approved, I will include this with the feature request PR.

**Comment by lbluque** [comment]
Thanks for caching this. Seems like no harm to me, so feel free to remove, the line: ```self.coef_, self.intercept_ = None, None```
