### ISSUE TITLE
Need to update orbitwise group L0 method and orbitwise hierarchy

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/sparse-lm#49]
**Is your feature request related to a problem? Please describe.**
Using L0 on each correlation function rather than orbit might be wrong for basis other than indicator. 
In the current code, orbit level hierarchy constraints have also not been implemented. (Or at least not merged.)

**Describe the solution you'd like**
Please describe the desired behavior.

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by lbluque** [comment]
Orbit-level hierarchy can be obtained using `GroupedL1L0` (at some point I will combine `L2L0` and `GroupedL2L0` into a single class see #17),
https://github.com/CederGroupHub/sparse-lm/blob/9e139383b0c7905cdc8a627b7665c5cf3c65cb6c/sparselm/model/miqp/_regularized_l0.py#L558

Or using `OverlapGroupLasso`,
https://github.com/CederGroupHub/sparse-lm/blob/9e139383b0c7905cdc8a627b7665c5cf3c65cb6c/sparselm/model/_lasso.py#L193

**Comment by qchempku2017** [comment]
> Orbit-level hierarchy can be obtained using `GroupedL2L0` (at some point I will combine `L2L0` and `GroupedL2L0` into a single class see #17),
> 
> https://github.com/CederGroupHub/sparse-lm/blob/9e139383b0c7905cdc8a627b7665c5cf3c65cb6c/sparselm/model/miqp/_regularized_l0.py#L558
> 
> Or using `OverlapGroupLasso`,
> 
> https://github.com/CederGroupHub/sparse-lm/blob/9e139383b0c7905cdc8a627b7665c5cf3c65cb6c/sparselm/model/_lasso.py#L193

There are still some confusion. We'd better talk about this in person.

**Comment by qchempku2017** [comment]
Turns out that the document strings of GroupL0 did not clearly indicate what it does. The doc strings have been updated.
