### ISSUE TITLE
Change the Estimator's default scorer from r2 score to root mean square error

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/sparse-lm#53]
**Is your feature request related to a problem? Please describe.**
Currently, sparse-lm inherits Estimator from sklearn's RegressorMixin, which means it uses r2_score as its default scorer. Although it is possible to convert from r2_score to RMSE, r2_scores are less interpretable as we usually present the errors of CE in terms of RMSE and CV RMSE. Besides, the standard deviation of r2_score cannot be directly converted to the standard deviation of RMSE, which we might need when selecting the optimal hyper-parameters using one-standard-error rule.   

**Describe the solution you'd like**
Overwrite the inherited scoring in model/_base.py by re-defining the "score" method to use root mean square error.

**Comment by lbluque** [comment]
Thanks @qchempku2017 

Why can't you just set the score parameter `score='neg_mean_squared_error'` ?

Do you just want to hard-code this as the default?

**Comment by qchempku2017** [comment]
> 
Yes, I think it would be better if we can hard code rmse as default.

**Comment by qchempku2017** [comment]
If you are not okay with changing the default, I can accept with setting score always to 'neg_mean_squared_error'

**Comment by lbluque** [comment]
Would setting it as default in our `CVSearch` class do it?
https://github.com/CederGroupHub/sparse-lm/blob/9e139383b0c7905cdc8a627b7665c5cf3c65cb6c/sparselm/optimizer.py#L29
