### ISSUE TITLE
Add suggestions to use SCIP for some users

### ISSUE THREAD

**Issue by qchempku2017** [CederGroupHub/sparse-lm#73]
**Is your feature request related to a problem? Please describe.**
Since gurobi requires license and installing gurobi on a computing cluster is not very easy, some users might want to use open-source optimizers. cvxpy now supports SCIP. We can add this in the documentations or README.md and refer users with specific needs to the corresponding cvxpy and SCIP doc pages.

**Comment by lbluque** [comment]
This is a good idea.

I would say a detailed description of installing and using different solvers can be added to the documentation as a full section.

In addition a brief statement can be added to the docstrings of the pertinent  MIQP classes.

**Comment by qchempku2017** [comment]
I have tested SCIP + pySCIPOpt solver with L2L0 and they worked perfectly. Another good news is that SCIP can be installed and configured with its python interface with conda in a single command:

`conda install --channel conda-forge pyscipopt`

So it is also possible to set SCIP up in the test environment.

**Comment by lbluque** [comment]
addressed in #93
