### ISSUE TITLE
Estimator objects have no attribute  '_preprocess_data'

### ISSUE THREAD

**Issue by kamronald** [CederGroupHub/sparse-lm#8]
When attempting to fit with an L0-L2 estimator, I encountered this issue. It cannot recognize a private method that is in the base Estimator class. Thought my code might just be outdated, but I have uninstalled and pip installed sparse-lm again, and the issue remains.

```
AttributeError                            Traceback (most recent call last)
/var/folders/nf/z3_007nd3ts4z1sjx0v0cxtr0000gn/T/ipykernel_11532/3441676329.py in <module>
----> 1 est.fit(wr.feature_matrix[unique_inds][:, 4:53], cen_ens)

~/miniconda3/envs/stat_mech/lib/python3.9/site-packages/sparselm/model/base.py in fit(self, X, y, sample_weight, *args, **kwargs)
     77                                                  dtype=X.dtype)
     78 
---> 79         X, y, X_offset, y_offset, X_scale = self._preprocess_data(
     80             X, y, fit_intercept=self.fit_intercept, normalize=self.normalize,
     81             copy=self.copy_X, sample_weight=sample_weight,

AttributeError: 'L2L0' object has no attribute '_preprocess_data'
```

**Comment by lbluque** [comment]
That's probably due to the recent scikit-learn interface changes. I think this is the same issue addressed in #6

Try using the latest code on the main branch (I haven't tagged with a version), or downgrade scikit-learn.

**Comment by kamronald** [comment]
Gotcha, I tried downgrading to sklearn=1.0.2 and it works, while a newer version will have that bug. Just made a PR to specify that in pyproject.toml

**Comment by kamronald** [comment]
Installed sparse-lm another way in editable mode, and this issue goes away. Seems like I was not getting the latest version of the code when doing "pip install sparse-lm", and "pip install sparse-lm --upgrade".

**Comment by qchempku2017** [comment]
The problem can be resolved by installing latest sparce-lm from git repo. Please mark as resolved.
